#!/usr/bin/env python3
"""Generate a premium-microsite build brief from the data/*.csv knowledge base.

Usage:
    python3 scripts/microsite_brief.py --list
    python3 scripts/microsite_brief.py --archetype practitioner-authority --name "Dr. Example"
    python3 scripts/microsite_brief.py --archetype consumer-brand-cpg --name "Banti Soda" \
        --kit playful-pop --stack vite-react-spa-prerendered --out docs/MICROSITE_BRIEF.md

The brief is a starting contract, not a deliverable. Every TODO(client) marker
must be replaced with a client-supplied fact before the site ships; the gate
script fails while any remain.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from microsite_search import exact_lookup, load_domain, search_domain  # noqa: E402

TOKEN_TODO = "TODO(client)"


def die(message: str) -> None:
    raise SystemExit(f"error: {message}")


def split_list(value: str) -> list[str]:
    """Split a comma-joined CSV cell into sentence-cased items."""
    items = [part.strip() for part in value.split(",") if part.strip()]
    return [item[0].upper() + item[1:] if item else item for item in items]


def resolve_section(name: str) -> dict | None:
    """Map an archetype's section label onto a canonical section recipe."""
    row = exact_lookup("section", name)
    if row:
        return row
    hits = search_domain("section", name.replace("-", " "), 1)
    return hits[0][1] if hits else None


def css_tokens(kit: dict) -> str:
    scale = kit["Type Scale"]
    display = scale.split(" display")[0].strip() if "display" in scale else "clamp(2.25rem, 1.4rem + 3.6vw, 4.5rem)"
    return f""":root {{
  /* palette — kit: {kit['Kit']} (contrast-checked against WCAG 2.2 AA) */
  --bg: {kit['Background']};
  --surface: {kit['Surface']};
  --ink: {kit['Ink']};
  --ink-muted: {kit['Muted Ink']};
  --line: {kit['Line']};
  --accent: {kit['Accent']};
  --on-accent: {kit['On Accent']};

  /* type */
  --font-display: '{kit['Heading Font']}', serif;
  --font-body: '{kit['Body Font']}', system-ui, sans-serif;
  --font-mono: '{kit['Mono Font']}', ui-monospace, monospace;
  --step-display: {display};
  --step-h2: clamp(1.75rem, 1.2rem + 2.2vw, 3rem);
  --step-h3: clamp(1.25rem, 1.05rem + 0.9vw, 1.75rem);
  --step-body: clamp(1rem, 0.97rem + 0.15vw, 1.125rem);
  --step-small: 0.875rem;
  --measure: 68ch;

  /* rhythm */
  --section-y: clamp(4rem, 2rem + 8vw, 9rem);
  --gutter: clamp(1.25rem, 0.75rem + 2vw, 3rem);
  --stack: 1.5rem;
  --radius: {kit['Radius']};
  --shadow: {kit['Shadow']};

  /* motion */
  --dur-fast: 180ms;
  --dur-base: 340ms;
  --dur-slow: 720ms;
  --ease: cubic-bezier(0.22, 1, 0.36, 1);
}}

@media (prefers-reduced-motion: reduce) {{
  *, *::before, *::after {{
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }}
}}"""


def render(arch: dict, kit: dict, stack: dict, budget: dict, name: str) -> str:
    sections = [s.strip() for s in arch["Section Order"].split(",") if s.strip()]
    tier = arch["Motion Tier"]
    motion_hits = search_domain("motion", tier.replace("-", " ") + " " + arch["Keywords"], 5)
    schema_types = [s.strip() for s in arch["Schema Types"].split(",") if s.strip()]
    proof = split_list(arch["Proof Requirements"])
    exclusions = split_list(arch["Exclusions"])

    out: list[str] = []
    add = out.append

    add(f"# Microsite build brief — {name}")
    add("")
    add(f"Archetype `{arch['Archetype']}` · brand kit `{kit['Kit']}` · stack `{stack['Recipe']}` · budget tier `{budget['Tier']}`")
    add("")
    add(f"Generated by `scripts/microsite_brief.py`. Replace every `{TOKEN_TODO}` before shipping — "
        "`scripts/microsite_gate.sh` fails while any remain.")
    add("")

    add("## 1. Outcome contract")
    add("")
    add(f"- **Audience:** {arch['Audience']}")
    add(f"- **Promise:** {TOKEN_TODO}: one sentence the client would sign their name to")
    add(f"- **Primary action:** {arch['Primary Action']}")
    add(f"- **Success signal:** {TOKEN_TODO}: the measurable event that means the site worked")
    add(f"- **Return trigger:** {TOKEN_TODO}: why a visitor would come back or forward the link")
    add(f"- **Mood:** {kit['Mood']}")
    add("")

    add("### Explicitly out of scope")
    add("")
    for item in exclusions:
        add(f"- {item}")
    add("- No accounts, roles, dashboards, or persistent user state (this is a microsite, not an application)")
    add("")

    add("## 2. Facts required from the client")
    add("")
    add("Nothing below may be generated, estimated, or filled with a plausible substitute.")
    add("")
    for item in proof:
        add(f"- [ ] {item}")
    add("")

    add("## 3. Section map")
    add("")
    add("| # | Section | Purpose | Motion | Required states |")
    add("|---|---|---|---|---|")
    for i, label in enumerate(sections, 1):
        recipe = resolve_section(label)
        if recipe:
            add(f"| {i} | `{label}` → {recipe['Section']} | {recipe['Purpose']} | {recipe['Motion Recipe']} | {recipe['Required States']} |")
        else:
            add(f"| {i} | `{label}` | {TOKEN_TODO}: no canonical recipe matched — define it | — | — |")
    add("")
    add("Query the full recipe for any row:")
    add("")
    add("```bash")
    add(f"python3 scripts/microsite_search.py \"{sections[0]}\" --domain section")
    add("```")
    add("")

    add("## 4. Design tokens")
    add("")
    add(f"Type pairing: **{kit['Heading Font']}** display / **{kit['Body Font']}** body / **{kit['Mono Font']}** mono. "
        f"Texture: {kit['Texture']}.")
    add("")
    add("```css")
    add(css_tokens(kit))
    add("```")
    add("")
    add("No literal hex or px values in components. If a value is not in this block, it does not belong in the design.")
    add("")

    add(f"## 5. Motion plan — {tier}")
    add("")
    add("| Recipe | Trigger | Duration | Reduced-motion end state |")
    add("|---|---|---|---|")
    for _, row in motion_hits:
        add(f"| `{row['Recipe']}` | {row['Trigger']} | {row['Duration']} | {row['Reduced Motion End State']} |")
    add("")
    add("Rules: transform and opacity only; one pinned section maximum; every effect has an end state under "
        "`prefers-reduced-motion: reduce`; above-the-fold content is never hidden behind a JS reveal.")
    add("")

    add("## 6. WebGL decision")
    add("")
    webgl = arch["WebGL Use"]
    if webgl == "none":
        add("Not in scope for this archetype. Adding a canvas requires a written justification of what the visitor "
            "understands from it that a photograph cannot convey.")
    else:
        add(f"Candidate pattern: `{webgl}`. Required regardless of pattern: `poster-first-loader` and `capability-gate`.")
        add("")
        add("```bash")
        add(f"python3 scripts/microsite_search.py \"{webgl.replace('-', ' ')}\" --domain webgl")
        add("python3 scripts/microsite_search.py \"poster capability gate\" --domain webgl --max-results 2")
        add("```")
        add("")
        add(f"Asset licence and provenance must be recorded before import. {TOKEN_TODO}: model source and licence.")
    add("")

    add("## 7. Structured data")
    add("")
    for schema in schema_types:
        add(f"- `{schema}` — every property must correspond to something visible on the page")
    add("")
    add("```bash")
    add(f"python3 scripts/microsite_search.py \"{schema_types[0]}\" --domain schema")
    add("```")
    add("")

    add("## 8. Stack and file plan")
    add("")
    add(f"**{stack['Recipe']}** — {stack['When To Choose']}")
    add("")
    add("```bash")
    for cmd in stack["Scaffold Commands"].split(";"):
        if cmd.strip():
            add(cmd.strip())
    add("```")
    add("")
    add(f"- Dependencies: {stack['Key Dependencies']}")
    add(f"- Prerender: {stack['Prerender Approach']}")
    add(f"- Routing: {stack['Routing']}")
    add(f"- Deploy: {stack['Deploy']}")
    add(f"- Watch out for: {stack['Gotchas']}")
    add("")
    add("```text")
    add("src/")
    add("  content/site.ts          # typed content: every string the client can change")
    add("  styles/tokens.css        # the block in section 4, single source of truth")
    add("  components/              # one folder per section from the map above")
    add("  lib/motion.ts            # Lenis + ScrollTrigger setup and matchMedia guards")
    add("public/")
    add("  og.jpg  favicon.svg  robots.txt  sitemap.xml")
    add("docs/")
    add("  MICROSITE_BRIEF.md  ASSET_LICENCES.md  CONTENT_GUIDE.md")
    add("```")
    add("")

    add(f"## 9. Performance budget — {budget['Tier']}")
    add("")
    add("| Metric | Budget |")
    add("|---|---|")
    for column in ("Initial JS (gzip)", "CSS (gzip)", "LCP Image", "Fonts", "Heavy Chunk", "LCP", "CLS", "INP", "Total Route Weight"):
        add(f"| {column} | {budget[column]} |")
    add(f"| Measured on | {budget['Measurement Profile']} |")
    add("")
    add(f"{budget['Notes']}")
    add("")

    add("## 10. Verification")
    add("")
    add("```bash")
    add("npm run build")
    add("scripts/microsite_gate.sh .")
    add("```")
    add("")
    add("Then, on the production build: four-viewport browser pass with a clean console, keyboard-only pass, "
        "`prefers-reduced-motion` pass, throttled-network pass, Lighthouse with the profile above, automated "
        "accessibility scan plus a manual screen-reader spot check, link and anchor check, structured-data "
        "validation, and a social-card render. Record the command and the outcome for each. A skipped check is a gap.")
    add("")

    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--archetype", "-a", help="archetype name from data/microsite-archetypes.csv")
    parser.add_argument("--name", "-N", default="Untitled site", help="project or client name")
    parser.add_argument("--kit", help="override the archetype's brand kit")
    parser.add_argument("--stack", help="override the archetype's stack recipe")
    parser.add_argument("--budget", help="override the archetype's budget tier")
    parser.add_argument("--out", "-o", help="write to this path instead of stdout")
    parser.add_argument("--list", action="store_true", help="list archetypes, kits, stacks and budget tiers")
    args = parser.parse_args(argv)

    if args.list:
        for domain, label in (("archetype", "Archetype"), ("brand", "Kit"), ("stack", "Recipe"), ("budget", "Tier")):
            rows, name_col = load_domain(domain)
            print(f"\n{label}s ({domain}):")
            for row in rows:
                summary = row.get("Keywords") or row.get("When To Choose") or ""
                print(f"  {row[name_col]:<28} {summary[:72]}")
        return 0

    if not args.archetype:
        parser.error("--archetype is required (see --list)")

    arch = exact_lookup("archetype", args.archetype)
    if arch is None:
        hits = search_domain("archetype", args.archetype.replace("-", " "), 3)
        suggestions = ", ".join(row["Archetype"] for _, row in hits) or "see --list"
        die(f"unknown archetype {args.archetype!r}. Closest: {suggestions}")

    kit = exact_lookup("brand", args.kit or arch["Brand Kit"])
    if kit is None:
        die(f"unknown brand kit {args.kit or arch['Brand Kit']!r}")
    stack = exact_lookup("stack", args.stack or arch["Stack Recipe"])
    if stack is None:
        die(f"unknown stack recipe {args.stack or arch['Stack Recipe']!r}")
    budget = exact_lookup("budget", args.budget or arch["Budget Tier"])
    if budget is None:
        die(f"unknown budget tier {args.budget or arch['Budget Tier']!r}")

    brief = render(arch, kit, stack, budget, args.name)

    if args.out:
        path = Path(args.out)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(brief, encoding="utf-8")
        todos = len(re.findall(re.escape(TOKEN_TODO), brief))
        print(f"Wrote {path} ({len(brief.splitlines())} lines, {todos} client facts to fill in)")
    else:
        sys.stdout.write(brief)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
