import { BrainCircuit, Check, Cloud, Cpu, Eye, Gauge, Sparkles, Wrench } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useProviderStore } from '@/stores/providers';
import { cn } from '@/lib/utils';

const FREE_PROVIDERS = [
  { vendorId: 'openrouter', icon: Cloud, model: 'openrouter/free', accent: 'from-cyan-400/20 via-blue-500/10 to-transparent', traits: ['vision', 'tools', 'reasoning'] },
  { vendorId: 'google', icon: Sparkles, model: 'gemini-3-flash-preview', accent: 'from-violet-400/20 via-fuchsia-500/10 to-transparent', traits: ['vision', 'tools', 'reasoning'] },
  { vendorId: 'ollama', icon: Cpu, model: 'qwen3-vl:8b', accent: 'from-emerald-400/20 via-teal-500/10 to-transparent', traits: ['vision', 'tools', 'reasoning'] },
] as const;

export function FreeModelDock() {
  const { t } = useTranslation('dashboard');
  const accounts = useProviderStore((state) => state.accounts);
  const defaultAccountId = useProviderStore((state) => state.defaultAccountId);
  const scrollToProviders = () => document.getElementById('provider-settings')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  return <section data-testid="free-model-dock" className="relative overflow-hidden rounded-[2rem] border border-black/[0.07] bg-surface-modal p-6 shadow-[0_24px_80px_rgba(15,23,42,0.08)] dark:border-white/[0.08]">
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_0%,rgba(34,211,238,0.12),transparent_32%),radial-gradient(circle_at_88%_10%,rgba(168,85,247,0.12),transparent_34%)]" />
    <div className="relative"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-700 dark:text-cyan-300"><Gauge className="h-4 w-4" />{t('freeDock.eyebrow')}</div><h2 className="text-3xl font-serif font-normal tracking-tight text-foreground">{t('freeDock.title')}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-foreground/60">{t('freeDock.description')}</p></div><button type="button" onClick={scrollToProviders} className="shrink-0 rounded-xl bg-foreground px-4 py-2.5 text-sm font-semibold text-background shadow-sm transition hover:-translate-y-0.5">{t('freeDock.configure')}</button></div>
      <div className="mt-6 grid gap-3 lg:grid-cols-3">{FREE_PROVIDERS.map((provider, index) => { const account = accounts.find((candidate) => candidate.vendorId === provider.vendorId && candidate.enabled); const isDefault = !!account && account.id === defaultAccountId; const Icon = provider.icon; return <button key={provider.vendorId} type="button" onClick={scrollToProviders} className="group relative overflow-hidden rounded-2xl border border-black/[0.06] bg-background/65 p-4 text-left transition hover:-translate-y-1 hover:border-cyan-400/30 dark:border-white/[0.08] dark:bg-white/[0.035]"><div className={cn('absolute inset-0 bg-gradient-to-br opacity-60', provider.accent)} /><div className="relative"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-black/[0.06] bg-white/75 dark:border-white/10 dark:bg-white/[0.08]"><Icon className="h-5 w-5" /></span><span className={cn('inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em]', account ? 'bg-emerald-500/12 text-emerald-700 dark:text-emerald-300' : 'bg-black/[0.05] text-foreground/50 dark:bg-white/[0.07]')}>{account && <Check className="h-3 w-3" />}{isDefault ? t('freeDock.default') : account ? t('freeDock.connected') : t('freeDock.available')}</span></div><p className="mt-5 text-sm font-semibold">{t(`freeDock.providers.${provider.vendorId}.name`)}</p><p className="mt-1 font-mono text-[11px] text-foreground/45">{account?.model || provider.model}</p><p className="mt-3 min-h-10 text-sm leading-5 text-foreground/60">{t(`freeDock.providers.${provider.vendorId}.description`)}</p><div className="mt-4 flex flex-wrap gap-1.5">{provider.traits.map((trait) => <span key={trait} className="inline-flex items-center gap-1 rounded-lg border border-black/[0.05] bg-white/60 px-2 py-1 text-[10px] font-semibold text-foreground/55 dark:border-white/[0.07] dark:bg-white/[0.04]">{trait === 'vision' ? <Eye className="h-3 w-3" /> : trait === 'tools' ? <Wrench className="h-3 w-3" /> : <BrainCircuit className="h-3 w-3" />}{t(`freeDock.traits.${trait}`)}</span>)}</div><div className="mt-4 flex items-center justify-between border-t border-black/[0.06] pt-3 text-[11px] dark:border-white/[0.07]"><span className="font-semibold text-emerald-700 dark:text-emerald-300">{t('freeDock.zeroTokenCost')}</span><span className="text-foreground/40">{t(`freeDock.priority.${index + 1}`)}</span></div></div></button>; })}</div>
    </div>
  </section>;
}
